// Generates public/js/data/stars.js from the Yale Bright Star Catalogue.
//
// Run once, by hand, and commit the output. The app itself stays build-free —
// this is a tool that produced a data file, not a step in serving it.
//
//   node tools/build-stars.mjs path/to/bsc5-short.json
//
// Source: https://github.com/brettonw/YaleBrightStarCatalog (Yale BSC5,
// positions for equinox and epoch J2000).

import { readFileSync, writeFileSync } from "node:fs";
import { CONSTELLATIONS, ASTERISMS } from "../public/js/data/constellations.js";

const MAG_LIMIT = 4.0;

// Bayer letters carry superscripts for the components of doubles — Albireo is
// β¹ Cyg, not β Cyg — so a figure asking for "β" has to match "β¹".
function baseBayer(bayer) {
  return bayer ? bayer.replace(/[¹²³\u2074-\u2079]/g, "") : bayer;
}

// Constellation figures reach for stars that are sometimes fainter than the
// display cut: the Little Dipper's bowl runs past magnitude 4.5. Keeping those
// regardless is cheaper than lowering the cut for the whole sky.
const required = new Set();
for (const c of CONSTELLATIONS) {
  for (const [a, b] of c.lines) {
    required.add(`${a}|${c.con}`);
    required.add(`${b}|${c.con}`);
  }
}
for (const ast of ASTERISMS) {
  for (const [bayer, con] of ast.stars) required.add(`${bayer}|${con}`);
}

const raw = readFileSync(process.argv[2], "utf8");
const rows = [...raw.matchAll(/\{[^{}]*\}/g)].map((m) => JSON.parse(m[0]));

// "06h 45m 08.9s" -> hours
function parseRA(text) {
  const [, h, m, s] = text.match(/(\d+)h\s*(\d+)m\s*([\d.]+)s/);
  return Number(h) + Number(m) / 60 + Number(s) / 3600;
}

// "-16° 42′ 58″" -> degrees
function parseDec(text) {
  const [, sign, d, m, s] = text.match(/([+-])(\d+)°\s*(\d+)′\s*(\d+)″/);
  const value = Number(d) + Number(m) / 60 + Number(s) / 3600;
  return sign === "-" ? -value : value;
}

const stars = rows
  .filter((r) => {
    if (!r.RA || !r.Dec || !r.V) return false;
    if (Number(r.V) <= MAG_LIMIT) return true;
    return r.B && r.C && required.has(`${baseBayer(r.B)}|${r.C}`);
  })
  .map((r) => ({
    ra: Number(parseRA(r.RA).toFixed(5)),
    dec: Number(parseDec(r.Dec).toFixed(4)),
    mag: Number(r.V),
    name: r.N || null,
    bayer: r.B || null,
    con: r.C || null,
  }))
  .sort((a, b) => a.mag - b.mag);

// Compact tuples rather than objects: this file ships to a phone.
const tuples = stars.map((s) =>
  `[${s.ra},${s.dec},${s.mag},${s.name ? JSON.stringify(s.name) : 0},${s.bayer ? JSON.stringify(s.bayer) : 0},${s.con ? JSON.stringify(s.con) : 0}]`
);

const output = `// Bright stars to magnitude ${MAG_LIMIT}, generated by tools/build-stars.mjs.
// DO NOT EDIT BY HAND — regenerate from the catalogue instead.
//
// Source: Yale Bright Star Catalogue (BSC5), positions for equinox and epoch
// J2000. Star positions here are catalogue data, not written from memory; the
// constellation figures in constellations.js are a separate matter and say so.
//
// Each entry is [rightAscensionHours, declinationDegrees, magnitude, name,
// bayer, constellation], with 0 standing in for an absent field to keep the
// file small.

export const STAR_FIELDS = ["ra", "dec", "mag", "name", "bayer", "con"];

export const STARS = [
${tuples.join(",\n")}
];

export function star(index) {
  const [ra, dec, mag, name, bayer, con] = STARS[index];
  return { ra, dec, mag, name: name || null, bayer: bayer || null, con: con || null };
}

export function allStars() {
  return STARS.map((_, i) => star(i));
}

// Look one up the way constellation figures refer to them: Bayer letter plus
// constellation, as in "alpha Ori".
export function findByBayer(bayer, con) {
  // Doubles carry superscripts — Albireo is catalogued as β¹ Cyg — so a figure
  // asking for β has to match it. Prefer an exact hit, then the brightest
  // component, which is the one the naked eye sees as the star.
  const strip = (b) => (b ? b.replace(/[¹²³\u2074-\u2079]/g, "") : b);

  let index = STARS.findIndex((s) => s[4] === bayer && s[5] === con);
  if (index === -1) {
    index = STARS.findIndex((s) => strip(s[4]) === bayer && s[5] === con);
  }
  return index === -1 ? null : star(index);
}
`;

writeFileSync("public/js/data/stars.js", output);
const extra = stars.filter((s) => s.mag > MAG_LIMIT).length;
console.log(
  `${stars.length} estrellas escritas: hasta magnitud ${MAG_LIMIT}, más ${extra} más débiles que exigen las figuras`
);
